export const USER_SYNC = 'USER_SYNC';
export const USER_OPENID = 'USER_OPENID';
export const USER_HOSP_DEPT_COCODES = 'USER_HOSP_DEPT_COCODES';
export const USER_FORCE_RERENDER = 'USER_FORCE_RERENDER';
