export const USER_SYNC = 'USER_SYNC';
export const USER_CONNECT_RESULT = 'USER_CONNECT_RESULT';
export const USER_HOSP_DEPT_COCODES = 'USER_HOSP_DEPT_COCODES';
export const USER_FORCE_RERENDER = 'USER_FORCE_RERENDER';
export const USER_SYNC_VIEWSET = 'USER_SYNC_VIEWSET';
